<?php

/**
 * Implements hook_feeds_plugins().
 * @see https://drupal.org/node/622700
 */
function feeds_xsd_xml_feeds_plugins() {
  $info['FeedsXSDParser'] = array(
    'name' => 'Feeds XML defined by XSD parser',
    'description' => 'Uses an XSD to configure field mappings.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsXSDParser',
      'file' => 'FeedsXSDParser.php',
      'path' => drupal_get_path('module', 'feeds_xsd_parser') . '/plugins',
    ),
  );
  
  return $info;
}

function feeds_xsd_parser_enable() {
    //clear the cache to display in Feeds as available plugin.
    cache_clear_all('plugins:feeds:plugins', 'cache');
}
