<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function feeds_zip_fetcher_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'feeds'  && $plugin_type == 'plugins') {
    return "plugins/$plugin_type";
  }
}
/**
 * Implements hook_feeds_plugins().
 */
function feeds_zip_fetcher_feeds_plugins() {
  $info = array();
  $info['FeedsArchiveFileFetcher'] = array(
    'name' => 'Archive File Fetcher',
    'description' => 'Import content from a local archive.',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'FeedsArchiveFileFetcher',
      'file' => 'FeedsArchiveFileFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_zip_fetcher') . '/plugins',
    ),
  );
  return $info;
}
/**
 * Implements hook_feeds_after_import().
 */
function feeds_zip_fetcher_feeds_after_import($source) {
  $state_fetcher = $source->state(FEEDS_FETCH);
  if (empty($state_fetcher->processed_archives)) {
    return;
  }
  foreach ($state_fetcher->processed_archives as $archive => $extract_dir) {
    // Delete archive.
    if (is_file($archive)) {
      drupal_unlink($archive);
    }
    // Delete extracted archive content and directory.
    if (is_dir($extract_dir)) {
      // Deletes all files and directories in the specified filepath recursively.
      file_unmanaged_delete_recursive($extract_dir);
    }
  }
}
